### ISSUE TITLE
Drupal help text needs updating

### ISSUE THREAD

**Issue by EdwardHinkle** [EdwardHinkle/indigenous-website#2]
From https://github.com/EdwardHinkle/indigenous-ios/issues/225

One detail on the help page re: the Drupal plugin: it doesn't allow you yet to use your own site to authenticate via IndieAuth. What's possible right now is to register/login to a drupal site via indieauth.com (or another service) (I'm working on that functionality though, coming hopefully soon)

**Comment by swentel** [comment]
I've put the indieauth part of Drupal in comments for iOS and Android
closing, I'll update later when it's in the Drupal plugin.
